### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by 9polaris9** [SmileJET/CAC4SSL#1]
Where is the file of "ACDC/data/all_slices/patient021_frame02_slice_6.h5"?  Can you share it?

**Comment by SmileJET** [comment]
> Where is the file of "ACDC/data/all_slices/patient021_frame02_slice_6.h5"? Can you share it?

You can get the data from https://github.com/HiLab-git/SSL4MIS/tree/master/data/ACDC.
