### ISSUE TITLE
Core code

### ISSUE THREAD

**Issue by xie-D-xq** [SmileJET/CAC4SSL#2]
Thank you for your wonderful work, Can you tell me what part of ypur core code is?

**Comment by xie-D-xq** [comment]
There has a question in CAC4SSL-main/code/network/unet-mso.py, You've constructed two Encoder classes that are the same, what are they for?

**Comment by SmileJET** [comment]
> There has a question in CAC4SSL-main/code/network/unet-mso.py, You've constructed two Encoder classes that are the same, what are they for?

Thank you for pointing this out! This was my mistake. While organizing the code, I mistakenly duplicated the Encoder class.
